- name: feature
  color: "0e8a16"
  description: "New feature"
- name: enhancement
  color: "a2eeef"
  description: "Enhancement"
- name: bug
  color: "d73a4a"
  description: "Bug"
- name: fix
  color: "fbca04"
  description: "Fix"
- name: docs
  color: "0075ca"
  description: "Documentation"
- name: chore
  color: "cfd3d7"
  description: "Maintenance"
